name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.9]
        node-version: [18]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      # Setup Python environment
      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Setup Node.js environment
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install frontend dependencies
        run: |
          cd frontend
          npm install

      # Install Playwright browsers and dependencies
      - name: Install Playwright browsers and dependencies
        run: |
          cd frontend
          npx playwright install --with-deps

      # Run Playwright tests (frontend)
      - name: Run Playwright tests
        run: |
          cd frontend
          npx playwright test

      # (Optionnel) Run Python backend tests if you have any
      - name: Run Python tests
        run: |
          pytest
