version: "3.9"

services:
  app:
    build: .
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - .:/app

  db:
    image: mysql:8.0
    container_name: mysql-container  # <-- indispensable si ton .env utilise ce nom
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: vehicles_db
    ports:
      - "3307:3306"  # <-- seulement si tu veux accéder à MySQL depuis ton host
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata:

